amcef/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('base.urls'))
]

base/urls.py
from struct import pack
from django import views
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('',views.home, name ="home"),
    path('users/', views.getData, name="users"),
    path('posts/', views.getPost, name="getPost"),
    path('post/<int:post_id>/', views.getPostById, name="getPostById"),
    path('updatePost/<int:post_id>/', views.updatePost, name="updatePost"),
    path('getPostByUsedId/<int:user_id>/', views.getPostByUsedId, name="getPostByUsedId"),
    path('createPost/', views.createPost, name="createPost"),
    path('deletePost/<int:post_id>/', views.deletePost, name="deletePost"),

]

base/models.py
from django.db import models


# Create your models here.

class  Post(models.Model):
    # id -> default by django (litesql) known as pk (PrimaryKey)
    userId = models.IntegerField()
    title = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField(null=True, blank=True)    

    def __str__(self) -> str:
        return ("userId: %d | title: %s" % (self.userId, self.title))

base/forms/postForm.py
from django.forms import ModelForm
from base.models import Post

class updateForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title','body']

class createForm(ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

base/views.py
from ast import Raise
from django.shortcuts import render, get_object_or_404, redirect
from .custom_code.requestCall import *
from .forms.postForm import *

# Create your views here.

def home(request):
    context = {
        'all_posts': Post.objects.all()
    }
    return render(request, 'base/home.html',context)

def getData(request):
    # get users
    list_of_users = getUSersId()
    
    
    return render(request, 'base/home.html') 

def getPost(request):
    dataFromReq = getReq(host="jsonplaceholder.typicode.com", url = "/posts" )

    context= {
        "data" : dataFromReq, 
    }
    return render(request, 'base/home.html', context) 

def getPostById(request,post_id):
    # search post in DB
    dataToReturn = {}
    try:
        myPost = Post.objects.get(pk=post_id)
        dataToReturn['id'] = myPost.pk
        dataToReturn['userId'] = myPost.userId
        dataToReturn['title'] = myPost.title
        dataToReturn['body'] = myPost.body

    except:
        postData = getReq(host="jsonplaceholder.typicode.com", url = "/posts/"+str(post_id))
        dataToReturn = {
            'id': postData['id'],
            'userId': postData['userId'],
            'title': postData['title'],
            'body':postData['body'],
        }
        
        Post.objects.create(pk=dataToReturn['id'],
        userId=dataToReturn['userId'],
        title=dataToReturn['title'],
        body=dataToReturn['body']
        )


    context= {
        "postById" : dataToReturn, 
    }
    return render(request, 'base/home.html', context) 

def getPostByUsedId(request,user_id):
    myPosts = Post.objects.filter(pk=user_id)
    print(myPosts,len(myPosts))

    # search post in DB
    try:
        myPosts = Post.objects.filter(userId=user_id)
        if len(myPosts) <1:
            raise "Post obj not found in DB!"
        
        # format data from DB accordingly to API data obj (for consistency )
        dataToReturn = []
        for myPost in myPosts:
            myPostfromReturn ={}
            myPostfromReturn['id'] = myPost.pk
            myPostfromReturn['userId'] = myPost.userId
            myPostfromReturn['title'] = myPost.title
            myPostfromReturn['body'] = myPost.body
            dataToReturn.append(myPostfromReturn)
         
    except:
        dataToReturn = getReq(host="jsonplaceholder.typicode.com", url = "/posts?userId="+str(user_id))

    context= {
        "data" : dataToReturn, 
    }
    return render(request, 'base/home.html', context) 




def updatePost(request,post_id):
    # ak nie je v DB ale je mimo tak pridaj do db
    # ak je post, zmen
    # ak get nahraj

    # is post in DB ?
    try:
        postToUpdate = get_object_or_404(Post,pk = post_id)

    # if not get info from API and save to db
    except:
        dataFromAPI = getReq(host="jsonplaceholder.typicode.com",url="/posts/"+str(post_id))
        print(dataFromAPI)
        postToUpdate = Post.objects.create(pk=dataFromAPI['id'],title=dataFromAPI['title'],body=dataFromAPI['body'],userId=dataFromAPI['userId'])
        postToUpdate.save()
    
    # if not post req
    if request.method != 'POST':
        context = {
        'myUPDATEform':updateForm(instance = postToUpdate),
        'myUPDATEform_id': post_id,
        }

        return render(request, 'base/post.html', context) 


    # If POST reQ
    myUpladeForm = updateForm(request.POST,instance = postToUpdate)
    if myUpladeForm.is_valid():
        # validate form and save post do DB
        myUpladeForm.save()
        # save post to 3nd party
        # to update create obj id/title/body/userId
        payload = {
            'id' : postToUpdate.pk,
            'title': postToUpdate.title,
            'body': postToUpdate.body,
            'userId': postToUpdate.userId
        }
        updateAPI(payload)
        # redirect
    else:
        print("Some error w saving obj to DB")

    return redirect('base:home')



def createPost(request):
    if request.method == 'POST':
        myform = createForm(request.POST)
        if myform.is_valid():
            # pre-save to DB
            presaved = myform.save(commit=False)
            # check if userId is valid, bc. we are not able to create new Users: 
            list_of_userIds= getUSersId()
            if presaved.userId in list_of_userIds:
                presaved.save()
            else: 
                Raise ("UserId not found during createPost")


            # save to api after succesfully save to local DB
            payload = {
                'title' : presaved.title,
                'body' : presaved.body,
                'userId': presaved.userId 
            }
            if createAPI(payload):
                return redirect('base:home')
            else:
                Raise ("Some error with creating creating API post")
    else:
        myform = createForm()
    
    context = {
        'myUpladeForm':myform,
    }
    return render(request, 'base/post.html', context) 

def deletePost(request, post_id):
    # get Post obj and delete it from DB
    mypost = get_object_or_404(Post,pk=post_id)
    mypost.delete()

    # delete Post from 3nd party API
    deleteAPI(post_id)

    return redirect('base:home')

base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block bs %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'base/styles.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">AMCEF-test</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class ="nav navbar-nav to-the-middle" style="width:90%;">
                <li>
                    <div>
                        <input class="byidclass" type="text" placeholder="Get post by id..."></input>
                        <input type="submit" class="btn btn-primary navbar-btn" value="Get By ID" onclick="getpostbyid('byidclass')"></input>
                    </div>
                </li>
                <li>
                    <div>
                        <input class="byuseridclass" type="text" placeholder="Get post by userID..."></input>
                        <input type="submit" class="btn btn-primary navbar-btn" value="Get By userId" onclick="getpostbyuserid('byuseridclass')"></input>
                    </div>
                </li>
                <li>
                    <div style="height: 100%; display: flex; align-items: center;">
                        <a href="{% url 'base:createPost' %}" class="btn btn-warning mybtn" >Create post</a>
                    </div>
                </li>
            </ul>
          </div>
        </div>
      </nav>
     
    {% block body %}
    {% if postById %}
    <div class="container justify-content-center">
        <div class="panel panel-success" style="margin:2em;">
            <div class="panel-heading">{{postById.id}}.) {{postById.title}}</div>
            <div class="panel-body">{{postById.body}}<br>
                <span style="color:cornflowerblue">userID:{{postById.userId}}</span>
            </div>
            <div style="margin: 1em;">
                <a href="{% url 'base:updatePost' postById.id %}" class="btn btn-outline-primary">Update</a>
                <a href="{% url 'base:deletePost' postById.id %}" class="btn btn-outline-dark">Delete</a>
            </div>
        </div>
    </div>
    
    {% endif %}

    <div class="container justify-content-center">
        {% for post in data%}
        <div class="panel panel-info" style="margin:2em;">
            <div class="panel-heading">{{post.id}}.) {{post.title}}</div>
            <div class="panel-body">{{post.body}}<br>
            <span style="color:cornflowerblue">userID:{{post.userId}}</span></div>
            <div style="margin: 1em;">
                <a href="{% url 'base:updatePost' post.id %}" class="btn btn-outline-primary">Update</a>
                <a href="{% url 'base:deletePost' post.id %}" class="btn btn-outline-dark">Delete</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

    
    {% if all_posts%}
    <div class="container justify-content-center">
        <h1>Posts in local DB:</h1>
        {% for post in all_posts%}
        <div class="panel panel-info" style="margin:2em;">
            <div class="panel-heading">{{post.id}}.) {{post.title}}</div>
            <div class="panel-body">{{post.body}}<br>
            <span style="color:cornflowerblue">userID:{{post.userId}}</span></div>
            <div style="margin: 1em;">
                <a href="{% url 'base:updatePost' post.id %}" class="btn btn-outline-primary">Update</a>
                <a href="{% url 'base:deletePost' post.id %}" class="btn btn-outline-dark">Delete</a>
            </div>
        </div>
        {% endfor %}
    </div>

    {% endif %}
    <script>
        var getpostbyid = (idofsearch) =>{
            var valueToSearch  = document.getElementsByClassName(idofsearch)[0].value;
            var url=(window.origin+"/api/post/"+valueToSearch);
            window.location.replace(url);

        }

        var getpostbyuserid = (idofsearch) =>{
            var valueToSearch  = document.getElementsByClassName(idofsearch)[0].value;
            var url=(window.origin+"/api/getPostByUsedId/"+valueToSearch);
            window.location.replace(url);

        }
    </script>
</body>
</html>

base/templates/base/post.html
{% extends "./home.html" %}


{% block body%}

{% if myUpladeForm%}
<div class="container justify-content-center">
    <form action="{% url 'base:createPost'%}" method="post">
        {% csrf_token %}
        {% load crispy_forms_tags %}
        {{myUpladeForm|crispy}}
        <input type="submit" class="btn btn-primary" value="Submit!">
    </form>
</div>
{% endif %}

{% if myUPDATEform %}
<div class="container justify-content-center">
    <form action="{% url 'base:updatePost' myUPDATEform_id %}" method="post">
        {% csrf_token %}
        {% load crispy_forms_tags %}
        {{myUPDATEform|crispy}}
        
        <input type="submit" class="btn btn-primary" value="Submit!">

    </form>
</div>
{% endif %}
{% endblock %}